### ISSUE TITLE
pgapi_get_redirect_url

### ISSUE THREAD

**Issue by sergeypavlenko** [itpatrol/pgapi#32]
Hi

In 7.x module version file paypal/pg_paypal.module:

```php
$form['return'] = array(
    '#type' => 'hidden',
    '#value' => url(pgapi_get_redirect_url($t), array('absolute' => TRUE)),
  );
```

But 7.x version not have function pgapi_get_redirect_url(). This function delete. And module pgapi not work.

What url will indicated for "return" url ?

**Comment by Gormartsen** [comment]
Fixed
